#!/bin/bash
#@AIM : Afficher les processus et leurs enfants sous forme d'arborescence, trier par PID, avec les arguments de commande.
#@AUTHORS :
#   - GOURILLON Nicolas
#@PARAMS :
#   - Aucun param
#@MODIF : 
#   - Changement de la mise en forme

pstree -hapsun
